n = int(input('Digite um número entre 0 e 9999: '))
u = str(int(10000 + n))
d = str(int(10000 + n))
c = str(int(10000 + n))
m = str(int(10000 + n))
print('O número {} possui, {} milhares.'.format(n, u[1]))
print('O número {} possui, {} centenas. '.format(n, d[2]))
print('O número {} possui, {} dezenas. '.format(n, c[3]))
print('O número {} possui, {} unidades.'.format(n, m[4]))
