nome=input('\033[2;36;40mqual o seu nome?')
resultado=print('olá, seja bem vindo',nome)
idade=input('você poderia me passar sua idade para prosseguir?')
fim=print('muito bem',nome,'de',idade,'anos de idade, voce passou no teste')
prox=print('fera bicho')
